# A.4 Backward Algorithm

In this assignment, we are going to improve our codes in PattRecClasses and implement forward algorithm inside MarkovChain code as well as functions such as logprob and prob in Guassian in order to generate proper input values for forward algorithm.

In [1]:
from PattRecClasses import DiscreteD, GaussD, HMM, MarkovChain, Px_calc, gauss_logprob
from matplotlib import pyplot as plt

import numpy as np

## 1-Verify The Implementation

### 1.1- Finite Markov Chain Test with MarkovChain/backward

In [2]:
q = np.array( [ 1, 0 ] )
A = np.array( [ [ 0.9 , 0.1, 0],[0, 0.9, 0.1] ] )

mc = MarkovChain(q,A) 

x = np.array([-0.2, 2.6, 1.3])

g1 = GaussD( means=[0], stdevs=[1] )   # Distribution for state = 1
g2 = GaussD( means=[3], stdevs=[2] )   # Distribution for state = 2

state_dists = [g1, g2]

P, scale_factor = Px_calc(state_dists, x )
Px = P * scale_factor

[ahat, c] = mc.forward(Px)
c = np.array([1, 0.1625, 0.8266, 0.0581])

print("Px matrix:")
print(Px)
print("ahat values:")
print(ahat)
print("c values:")
print(c)

bhat = mc.backward(Px,c)

print("Bhat matrix:", bhat)


Px matrix:
[[1.         0.06947052 1.        ]
 [0.14182701 1.         0.81107303]]
ahat values:
[[1.         0.38470424 0.41887466]
 [0.         0.61529576 0.58112534]]
c values:
[1.     0.1625 0.8266 0.0581]
(2, 3)
(2, 3)
(2, 3)
1 0 0
1 0 1
1 1 0
1 1 1
0 0 0
0.06497976063597927
0 0 1
0.9353573661183536
0 1 0
0 1 1
Bhat matrix: [[0.93535737 1.03928596 0.        ]
 [8.4182163  9.35357366 2.08222888]]


### 1.2-Infinite Markov Chain Test with MarkovChain/forward

In [3]:
A_inf = np.array( [ [ 0.9 , 0.1], [0.1, 0.9] ] )
mc_inf = MarkovChain(q,A_inf) 

[ahat_inf, c_inf] = mc_inf.forward(Px)

print("Px matrix:")
print(Px)
print("ahat_inf values:")
print(ahat_inf)
print("c_inf values:")
print(c_inf)

Px matrix:
[[1.         0.06947052 1.        ]
 [0.14182701 1.         0.81107303]]
ahat_inf values:
[[1.         0.38470424 0.45913586]
 [0.         0.61529576 0.54086414]]
c_inf values:
[1.         0.16252347 0.88811053]


### 1.3-Probability of Observed Sequence with HMM/logprob

In [4]:
h  = HMM( mc, state_dists)
obs_prob = h.logprob(x)
print("observation probability")
print(obs_prob)

observation probability
-9.187726979475208


#### The same case with infinite markov chain

In [5]:
h  = HMM( mc_inf, state_dists)
obs_prob = h.logprob(x)
print("observation probability for infinite HMM")
print(obs_prob)

observation probability for infinite HMM
-6.2705547326057935
