# A.3 Forward Algorithm

In this assignment, we are going to improve our codes in PattRecClasses and implement forward algorithm inside MarkovChain code as well as functions such as logprob and prob in Guassian in order to generate proper input values for forward algorithm.

In [1]:
from PattRecClasses import DiscreteD, GaussD, HMM, MarkovChain, Px_calc, gauss_logprob
from matplotlib import pyplot as plt

import numpy as np

## 1-Testing Px_calc

In this step, before we get into forward algorithm, we will be validating our function called Px_calc which calculates Px matrix that is going to be used as an input in forward algorithm.

In [2]:
x = np.array([0.2, 0.5, 0.3])

g1 = GaussD( means=[0], stdevs=[1] )   # Distribution for state = 1
g2 = GaussD( means=[3], stdevs=[2] )   # Distribution for state = 2



state_dists = [g1, g2]
print(x.size)
print(len(state_dists))
print(type(x))
print(type(state_dists))

#testing of prob function in GaussD

prob_x1_g1 = g1.prob(x[0])
prob_x2_g1 = g1.prob(x[1])
prob_x3_g1 = g1.prob(x[2])

prob_x1_g2 = g2.prob(x[0])
prob_x2_g2 = g2.prob(x[1])
prob_x3_g2 = g2.prob(x[2])

print("Individual probabilities of series of x in each distribution")
print("prob for x1 in g1 :" + str(prob_x1_g1))
print("prob for x2 in g1 :" +str(prob_x2_g1))
print("prob for x3 in g1 :" +str(prob_x3_g1))

print("prob for x1 in g2 :" +str(prob_x1_g2))
print("prob for x2 in g2 :" +str(prob_x2_g2))
print("prob for x3 in g2 :" +str(prob_x3_g2))

#testing of Px_calc 

P, scale_factor = Px_calc(x, state_dists)

Px = P * scale_factor

print("Px matrix is calculated as:")
print(Px)

3
2
<class 'numpy.ndarray'>
<class 'list'>
Individual probabilities of series of x in each distribution
prob for x1 in g1 :[0.39104269]
prob for x2 in g1 :[0.35206533]
prob for x3 in g1 :[0.38138782]
prob for x1 in g2 :[0.07486373]
prob for x2 in g2 :[0.09132454]
prob for x3 in g2 :[0.08019166]
Px matrix is calculated as:
[[1.         0.19144644]
 [1.         0.25939658]
 [1.         0.21026278]]


### Comparison of Px_calc and gauss_logprob

In [3]:
print("Px matrix is calculated from Px_calc as:")
print(Px)
print("P matrix is calculated from Px_calc as:")
print(P)
print("log(P) matrix :")
print(np.log(P))

Px_logprob = gauss_logprob(state_dists, x.reshape(1,-1))

print("Px matrix is calculated from gauss_logprob as:")
print(Px_logprob)




Px matrix is calculated from Px_calc as:
[[1.         0.19144644]
 [1.         0.25939658]
 [1.         0.21026278]]
P matrix is calculated from Px_calc as:
[[0.39104269 0.07486373]
 [0.35206533 0.09132454]
 [0.38138782 0.08019166]]
log(P) matrix :
[[-0.93893853 -2.59208571]
 [-1.04393853 -2.39333571]
 [-0.96393853 -2.52333571]]
Px matrix is calculated from gauss_logprob as:
[[-0.93893853 -1.04393853 -0.96393853]
 [-2.59208571 -2.39333571 -2.52333571]]


## 2-Verify The Implementation

### 2.1- Finite Markov Chain Test with MarkovChain/forward

In [8]:
q = np.array( [ 1, 0 ] )
A = np.array( [ [ 0.9 , 0.1, 0],[0, 0.9, 0.1] ] )

mc = MarkovChain(q,A) 

x = np.array([-0.2, 2.6, 1.3])

g1 = GaussD( means=[0], stdevs=[1] )   # Distribution for state = 1
g2 = GaussD( means=[3], stdevs=[2] )   # Distribution for state = 2

state_dists = [g1, g2]

P, scale_factor = Px_calc(x, state_dists)
Px = P * scale_factor

[ahat, c] = mc.forward(Px)

print(Px)
print(ahat)
print(c)

print("new calculation")
[ahat, c] = mc.forward(Px_logprob.transpose())
print(Px_logprob)
print(ahat)
print(c)

[[1.         0.14182701]
 [0.06947052 1.        ]
 [1.         0.81107303]]
[[1.         0.38470424 0.41887466]
 [0.         0.61529576 0.58112534]]
[1.         0.16252347 0.82658096 0.05811253]
new calculation
[[-0.93893853 -1.04393853 -0.96393853]
 [-2.59208571 -2.39333571 -2.52333571]]
[[1.         0.79698194 0.51080755]
 [0.         0.20301806 0.48919245]]
[-0.93893853 -1.17887825 -1.35357719  0.04891925]


### 2.2-Infinite Markov Chaint Test with MarkovChain/forward

In [5]:
A_inf = np.array( [ [ 0.9 , 0.1], [0.1, 0.9] ] )
mc_inf = MarkovChain(q,A_inf) 

[ahat_inf, c_inf] = mc_inf.forward(Px)

print(Px)
print(ahat_inf)
print(c_inf)

[[1.         0.14182701]
 [0.06947052 1.        ]
 [1.         0.81107303]]
[[1.         0.38470424 0.45913586]
 [0.         0.61529576 0.54086414]]
[1.         0.16252347 0.88811053]


### 2.3-Probability of Observed Sequence with HMM/logprob

In [6]:
h  = HMM( mc, state_dists)
obs_prob = h.logprob(x)
print(obs_prob)

-9.187726979475208
