# A.3 Forward Algorithm

In this assignment, we are going to improve our codes in PattRecClasses and implement forward algorithm inside MarkovChain code as well as functions such as logprob and prob in Guassian in order to generate proper input values for forward algorithm.

In [1]:
from PattRecClasses import DiscreteD, GaussD, HMM, MarkovChain, Px_calc
from matplotlib import pyplot as plt

import numpy as np

## 1-Testing Px_calc

In this step, before we get into forward algorithm, we will be validating our function called Px_calc which calculates Px matrix that is going to be used as an input in forward algorithm.

In [2]:
x = np.array([0.2, 0.5, 0.3])

g1 = GaussD( means=[0], stdevs=[1] )   # Distribution for state = 1
g2 = GaussD( means=[3], stdevs=[2] )   # Distribution for state = 2



state_dists = [g1, g2]
print(x.size)
print(len(state_dists))
print(type(x))
print(type(state_dists))

#testing of prob function in GaussD

prob_x1_g1 = g1.prob(x[0])
prob_x2_g1 = g1.prob(x[1])
prob_x3_g1 = g1.prob(x[2])

prob_x1_g2 = g2.prob(x[0])
prob_x2_g2 = g2.prob(x[1])
prob_x3_g2 = g2.prob(x[2])

print("Individual probabilities of series of x in each distribution")
print("prob for x1 in g1 :" + str(prob_x1_g1))
print("prob for x2 in g1 :" +str(prob_x2_g1))
print("prob for x3 in g1 :" +str(prob_x3_g1))

print("prob for x1 in g2 :" +str(prob_x1_g2))
print("prob for x2 in g2 :" +str(prob_x2_g2))
print("prob for x3 in g2 :" +str(prob_x3_g2))

#testing of Px_calc 

Px = Px_calc(x, state_dists)

print("Px matrix is calculated as:")
print(Px)

3
2
<class 'numpy.ndarray'>
<class 'list'>
Individual probabilities of series of x in each distribution
prob for x1 in g1 :[0.39104269]
prob for x2 in g1 :[0.35206533]
prob for x3 in g1 :[0.38138782]
prob for x1 in g2 :[0.07486373]
prob for x2 in g2 :[0.09132454]
prob for x3 in g2 :[0.08019166]
Px matrix is calculated as:
[[1.         0.19144644]
 [1.         0.25939658]
 [1.         0.21026278]]


## 2-Verify The Implementation

In [3]:
q = np.array( [ 1, 0 ] )
A = np.array( [ [ 0.9 , 0.1, 0],[0, 0.9, 0.1] ] )

mc = MarkovChain(q,A) 

x = np.array([-0.2, 2.6, 1.3])

g1 = GaussD( means=[0], stdevs=[1] )   # Distribution for state = 1
g2 = GaussD( means=[3], stdevs=[2] )   # Distribution for state = 2

state_dists = [g1, g2]

Px = Px_calc(x, state_dists)

[ahat, c] = mc.forward(Px)

print(Px)
print(ahat)
print(c)


[[1.         0.14182701]
 [0.06947052 1.        ]
 [1.         0.81107303]]
[[1.         0.38470424 0.41887466]
 [0.         0.61529576 0.58112534]]
[1.         0.16252347 0.82658096 0.05811253]
